name: Check PR using Sourcery
permissions:
  contents: read

on: pull_request

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.WIFITE }}
          diff_ref: ${{ github.event.pull_request.base.sha }}
